---
title: "Grafiken - Fragebogen Team Tau"
author: "Tau Mitglieder"
date: 31.12.2022
---

---
# You can render it with the commands below:
# 
# > library(rmarkdown)
# > render("Grafiken.Rmd", c("html_document", "pdf_document"))
---

```{r echo=FALSE}
# Add packages you need here!
library(knitr)
```

```{r echo=FALSE, results='hide'}
tau <- read.csv('tau.csv')
str(tau)
```

## Barplot bzgl. Betroffenheit und Einfluss auf Studiendauer

```{r echo=FALSE}
op <- par(no.readonly = TRUE) # the whole list of settable par's.
par(cex.main=1, cex.axis=.8, cex.lab=.8, mar = c(2.5, 4.3, 2.3, .3)) 

barplot(table(tau$Betroffenheit),
        names.arg = c("Überhaupt nicht betroffen", "leicht betroffen",
                      "stark betroffen"),
        ylab = "Anzahl der Studierenden", ylim = c(0,30), las = 1,
        main = "Wie betroffen von der Energiekrise fühlen sich die Studenten?")
par(op)
```


```{r echo=FALSE}
op <- par(no.readonly = TRUE) # the whole list of settable par's.
par(cex.main=1, cex.axis=.8, cex.lab=.8, mar = c(2.5, 4.3, 2.3, .3)) 

barplot(table(tau$Einfluss.Studiendauer),
        names.arg = c("stark negativ", "leicht negativ", "gar nicht",
                      "leicht positiv", "stark positiv"),
        ylab = "Anzahl der Studienrenden", ylim = c(0,25), las = 1,
        main = "Wie beeinflussen wie Preissteigerungen die Studiendauer der Studenten?")
par(op)
```


## Verteilung von Veränderung der Ausgaben

```{r echo=FALSE}
ausgabe <- tau[seq(3,9)]
library(stringr)
cnames <- colnames(ausgabe)
cnames <- str_replace(cnames, "Ausgabe\\.", "")
cnames <- str_replace(cnames, "\\.", "\n/ ")
colnames(ausgabe) <- cnames
ausgabe <- na.omit(ausgabe)
rownum <- nrow(ausgabe)
for( i in seq(-2, 2) ) {
    ausgabe <- rbind(ausgabe, rep(i, ncol(ausgabe)))
}
ausgabe <- ausgabe[,order(colMeans(ausgabe))] # nach Mittelwert ordnen
ratio <- (apply(ausgabe, 2, table)-1)/rownum

op <- par(no.readonly = TRUE) # the whole list of settable par's.
par(cex = 0.5, las = 1, mar = c(3, 6.5, .4, 2)) # Groesse der Beschriftung, horizontale Labels
library(RColorBrewer) # Paket für Farbverlauf Gruen -> Gelb -> Rot
barplot(ratio, 
        horiz = TRUE, # Horizontaler Barplot
        col = brewer.pal(5,"RdYlGn")[5:1], # Farben (richtig sortieren)
        xaxt = "n", yaxt = "n") # Achsen zunaechst nicht plotten
# x-Achse:
axis(1, at = seq(0, 1, length.out=11), labels = c(paste(10*0:10, "%", sep ="")))
# y-Achse (Namen = Variablnamen)
axis(2, at = seq(.75,7.96, length.out = ncol(ausgabe)), labels = colnames(ausgabe))
par(op)
```


## Covarianz von Ausgaben

```{r echo=FALSE, results='asis'}
ausgabe <- tau[seq(3,9)]
cnames <- colnames(ausgabe)
cnames <- str_replace(cnames, "Ausgabe\\.", "")
cnames <- str_replace(cnames, "\\.", "/")
colnames(ausgabe) <- cnames
kable(cov(na.omit(ausgabe)), digits=3)
```

---
# kabel example
# ```{r echo=FALSE, results='asis'}
# library(knitr)
# kable(table(tau$Betroffenheit))
# ```
---

## Änderung des Verhaltens

```{r echo=FALSE}
op <- par(no.readonly = TRUE) # the whole list of settable par's.
par(cex.main=1, cex.lab=.9, mfrow = c(3, 2), mar = c(2.5, 4.3, 2.3, .3)) 

barplot(table(tau$Verhalten.Angebote), names.arg = c("Nein", "Ja"),
        ylab = "Anzahl der Studierenden", ylim = c(0,40),
        main = "Ich achte mehr auf Angebote")

barplot(table(tau$Verhalten.Alternativen), names.arg = c("Nein", "Ja"),
        ylab = "Anzahl der Studierenden", ylim= c(0,40),
        main = "Ich nutze günstigere Alternativen")
        
barplot(table(tau$Verhalten.Anschaffungen), names.arg = c("Nein", "Ja"),
        ylab = "Anzahl der Studierenden", ylim = c(0,40),
        main = "Ich stelle weniger dringende Anschaffungen zurück")

barplot(table(tau$Verhalten.Kochen), names.arg = c("Nein", "Ja"),
        ylab = "Anzahl der Studierenden", ylim = c(0,40),
        main = "Ich koche mehr selbst")

barplot(table(tau$Verhalten.Energie.sparen), names.arg = c("Nein", "Ja"),
        ylab = "Anzahl der Studierenden", ylim = c(0,40),
        main = "Ich spare Energie")

barplot(table(tau$Verhalten.Wasser.sparen), names.arg = c("Nein", "Ja"),
        ylab = "Anzahl der Studierenden", ylim = c(0,40),
        main = "Ich spare Wasser")
par(op)
```
